language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t avijitpaul/docker-react .
  
script:
  - docker run -e CI=true avijitpaul/docker-react npm run test