version: '3'
services: 
    react-app:
        build:
            dockerfile: Dockerfile.dev
            context: .
        ports: 
            - "6000:3000"
        volumes: 
            - /app/node_modules
            - .:/app
    test-runner:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        volumes: 
            - .:/app
            - /app/node_modules
        command: ["npm", "test"]
